config/routes.rb
Rails.application.routes.draw do
  resources :counts, only: [:index, :create]
  root to: 'counts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/count.rb
class Count < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/counts_controller.rb
class CountsController < ApplicationController
  def index
    @count = Count.all
    @counter = @count.length
  end

  def create
    Count.create(count_params)
    @counter = Count.all.length
    # render json: { count: @counter }
    redirect_to root_path
  end

  private
  def count_params
    params.permit()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counts_helper.rb
module CountsHelper
end

app/views/counts/index.html.erb
<div class="count-number">
  <%= "#{@counter}F" %>
<div>


<div class="count-form">
  <%= form_with(model: @count, url: counts_path, local: true, method: :post) do |f| %>
  <%= f.submit '(￣ー￣)ｂ' %>
  <%# <div id="count-btn">
    aaa
  </div> %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Counter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>